Structure update 2
dearlordlt/exadel-sandbox-2021-fe pull request #41
Opened 2021-11-21 12:25 UTC by mikheil-gel

create modules for dashboard and login;
move dashboard pages folders to dashboard folder;
make dashboard pages child routes of "/dashboard";

2021-11-21 17:28 UTC, Mirzakobil approved these changes

2021-11-22 07:48 UTC, dearlordlt requested changes

2021-11-22 07:48 UTC, dearlordlt commented on src/app/components/dashboard/letters/create-letters-temp/create-letters-temp.component.ts
> +  get f() {
terrible function name

2021-11-22 07:48 UTC, dearlordlt commented on src/app/components/login/login.component.ts
>    }
Not a good idea to let user know that username is incorrect or specifically password is incorrect, should be one error for both

2021-11-22 07:58 UTC, simassimonas commented on src/app/components/dashboard/shared/dashboard-header/dashboard-header.component.scss
> +}
As this part is left empty for the future to implement, maybe it's worth to create an issue for it so we don't forget about it?

2021-11-22 07:59 UTC, simassimonas approved these changes

2021-11-22 08:57 UTC, GZardiashvili approved these changes

2021-11-22 12:08 UTC, merged